# Generated by Django 5.2.4 on 2025-08-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'services'},
        ),
    ]
