# Generated by Django 5.2.4 on 2025-07-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_projects', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url_demo_live',
            field=models.URLField(blank=True, null=True),
        ),
    ]
