# Generated by Django 5.2.4 on 2025-07-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_projects', '0003_blog_url_demo_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url_demo_live',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url_github',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
