# Generated by Django 5.2.4 on 2025-07-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_projects', '0004_alter_blog_url_demo_live_alter_blog_url_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url_github',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
